// This file was autogenerated by ../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../FireAdmin/dev/fireadmin.js', ['fa.utils'], [], false);
goog.addDependency('../../../FireAdmin/dev/init.js', ['fa.init'], [], false);
